let S,tok=sessionStorage.tok||'',view='setup',snaps=[],tmp={};
const ROLES=['Batsman','Wicket-Keeper','Bowler','All-rounder'],P0=()=>({runs:0,wd:0,nb:0,out:0,ro:0,who:'st'});let pend=P0();
const ropt=(x=true)=>Object.entries(RN).slice(0,x?undefined:-1).map(([k,n])=>`<option value=${k}>${n}</option>`).join('');
async function save(){const r=await fetch('/api/state',{method:'POST',headers:{'x-token':tok},body:JSON.stringify(S)});if(r.status==401)logout()}
function logout(){tok=sessionStorage.tok='';draw()}
function commit(){save();draw()}
async function boot(){S=await(await fetch('/api/state')).json();draw()}
async function login(e){e.preventDefault();const r=await fetch('/api/login',{method:'POST',body:JSON.stringify({password:e.target.pw.value})}),j=await r.json();if(j.token){tok=sessionStorage.tok=j.token;boot()}else $('#err').textContent=j.error}
function pick(cb,multi,ex=[]){const sel=new Set(),d=document.createElement('div');d.className='md';
 const paint=()=>{d.innerHTML=`<div class=box><h3>Select ${multi?'teams':'a team'}</h3>${S.teams.filter(t=>!ex.includes(t.id)).map(t=>`<button class="row ${sel.has(t.id)?'sel':''}" data-id="${t.id}">${logo(t)}${esc(t.name)}</button>`).join('')||'<p>Add teams first.</p>'}<div class=f>${multi?'<button class="btn p" data-ok>Done</button>':''}<button class=btn data-x>Cancel</button></div></div>`};
 paint();d.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.x!==undefined)return d.remove();if(b.dataset.ok!==undefined){d.remove();return cb([...sel])}const id=b.dataset.id;if(multi){sel.has(id)?sel.delete(id):sel.add(id);paint()}else{d.remove();cb(id)}};document.body.append(d)}
function shrink(file){return new Promise(res=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=96;const s=Math.min(im.width,im.height);c.getContext('2d').drawImage(im,(im.width-s)/2,(im.height-s)/2,s,s,0,0,96,96);res(c.toDataURL('image/png'))};im.src=URL.createObjectURL(file)})}
async function addTeam(e){e.preventDefault();const f=e.target,fl=f.l.files[0],c=cfg(S);if(S.teams.length>=c.maxTeams)return alert(`Team limit reached (${c.maxTeams}). Raise it in Tournament Setup.`);S.teams.push({id:uid(),name:f.n.value.trim(),logo:fl?await shrink(fl):'',players:[]});commit()}
function renTeam(id){const t=T(S,id),n=prompt('Team name',t.name);if(n){t.name=n;commit()}}
function delTeam(id){if(confirm('Delete this team?')){S.teams=S.teams.filter(t=>t.id!=id);commit()}}
function addP(e,id){e.preventDefault();const f=e.target,t=T(S,id),c=cfg(S),no=+f.no.value;if(t.players.length>=c.squad)return alert(`Squad is full (${c.squad} players).`);if(t.players.some(p=>p.no==no))return alert('That jersey number is already used in this team.');t.players.push({id:uid(),name:f.n.value.trim(),no,role:f.r.value});commit()}
function editP(tid,pid){const p=T(S,tid).players.find(p=>p.id==pid),n=prompt('Player name',p.name);if(n){p.name=n;p.no=+prompt('Jersey number',p.no)||p.no;commit()}}
function delP(tid,pid){const t=T(S,tid);t.players=t.players.filter(p=>p.id!=pid);commit()}
function reset(){if(confirm('Delete ALL teams, fixtures and matches?')){S={teams:[],groups:[],fixtures:[],live:null,history:[]};commit()}}
function sample(){if(S.teams.length&&!confirm('Add sample teams to the existing data?'))return;
 const N=['Byte Blasters','Kernel Kings','Pixel Pacers','Stack Strikers','Logic Lions','Circuit Chargers','Binary Bulls','Script Spinners'],ids=[];
 N.forEach(n=>{const id=uid();ids.push(id);S.teams.push({id,name:n,logo:'',players:Array.from({length:11},(_,k)=>({id:uid(),name:n.split(' ')[0]+' Player '+(k+1),no:k+1,role:ROLES[k<4?0:k==4?1:k<8?2:3]}))})});
 const gA=uid(),gB=uid();S.groups.push({id:gA,round:'r1',name:'Group A',teams:ids.slice(0,4)},{id:gB,round:'r1',name:'Group B',teams:ids.slice(4)});
 [[0,1,gA],[2,3,gA],[4,5,gB],[6,7,gB]].forEach(([a,b,g])=>S.fixtures.push({id:uid(),round:'r1',group:g,a:ids[a],b:ids[b]}));commit()}
function vTeams(){return`<h2>Teams and players</h2><form class=f onsubmit="addTeam(event)"><input name=n placeholder="Team name" required><input name=l type=file accept="image/png,image/jpeg" aria-label="Team logo"><button class="btn p">Add team</button></form><p class=f><button class=btn onclick=sample()>Load sample data</button><button class=btn onclick=reset()>Reset all data</button></p>`+S.teams.map(t=>`<div class="card pad"><div class="f sb"><span class=f>${logo(t)}<b>${esc(t.name)}</b></span><span class=f><button class=btn onclick="renTeam('${t.id}')">Rename</button><button class=btn onclick="delTeam('${t.id}')">Delete</button></span></div><form class=f onsubmit="addP(event,'${t.id}')" style="margin:8px 0"><input name=n placeholder="Player name" required><input name=no type=number min=0 placeholder="#" style="width:80px" required><select name=r>${ROLES.map(r=>`<option>${r}</option>`).join('')}</select><button class=btn>Add player</button></form><table>${[...t.players].sort((a,b)=>a.no-b.no).map(p=>`<tr><td>${p.no}. ${esc(p.name)} <span class=mut>${p.role}</span><td><button class=btn onclick="editP('${t.id}','${p.id}')">Edit</button> <button class=btn onclick="delP('${t.id}','${p.id}')">Delete</button></tr>`).join('')}</table></div>`).join('')}
function addG(e){e.preventDefault();const f=e.target,r=f.r.value,n=f.n.value.trim(),c=cfg(S);if(S.groups.filter(g=>g.round==r).length>=c.gpr)return alert(`${RN[r]} already has ${c.gpr} groups.`);pick(ids=>{if(ids.length!=c.tpg)return alert(`A group needs exactly ${c.tpg} teams.`);S.groups.push({id:uid(),round:r,name:n,teams:ids});commit()},true)}
function vGroups(){return`<h2>Groups</h2><form class=f onsubmit="addG(event)"><select name=r>${ropt(false)}</select><input name=n placeholder="Group A" required><button class="btn p">Select teams and create</button></form>`+S.groups.map(g=>`<div class="card pad f sb"><span><b>${esc(g.name)}</b> <span class=mut>${RN[g.round]}</span><br>${g.teams.map(id=>esc(T(S,id)?.name)).join(', ')}</span><button class=btn onclick="S.groups=S.groups.filter(x=>x.id!='${g.id}');commit()">Delete</button></div>`).join('')}
function addF(e){e.preventDefault();const f=e.target.elements,r=f.r.value,g=f.g.value;if(g&&S.groups.find(x=>x.id==g).round!=r)return alert('That group belongs to another round.');if(!g&&r!=Object.keys(RN).pop()&&S.groups.some(x=>x.round==r))return alert('Choose a group for this round.');pick(a=>pick(b=>{S.fixtures.push({id:uid(),round:r,group:g||null,a,b,date:f.d.value,time:f.t.value,venue:f.v.value.trim(),label:f.l.value.trim(),xiA:[],xiB:[]});commit()},false,[a]))}
function xiPick(fid,side){const f=S.fixtures.find(x=>x.id==fid),t=T(S,side=='A'?f.a:f.b),n=cfg(S).xi,sel=new Set(f['xi'+side]||[]),d=document.createElement('div');d.className='md';
 const paint=()=>{d.innerHTML=`<div class=box><h3>${esc(t.name)}: playing XI (${sel.size}/${n})</h3>${[...t.players].sort((a,b)=>a.no-b.no).map(p=>`<button class="row ${sel.has(p.id)?'sel':''}" data-id="${p.id}">${p.no}. ${esc(p.name)} <span class=mut>&nbsp;${p.role}</span></button>`).join('')||'<p>Add players first.</p>'}<div class=f><button class="btn p" data-ok>Save XI</button><button class=btn data-x>Cancel</button></div></div>`};paint();
 d.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.x!==undefined)return d.remove();if(b.dataset.ok!==undefined){if(sel.size!=n)return alert(`Select exactly ${n} players.`);f['xi'+side]=[...sel];d.remove();return commit()}const id=b.dataset.id;sel.has(id)?sel.delete(id):sel.add(id);paint()};document.body.append(d)}
function vFix(){const n=cfg(S).xi;return`<h2>Battles and fixtures</h2><form class=fg onsubmit="addF(event)"><select name=r>${ropt()}</select><select name=g><option value="">No group</option>${S.groups.map(g=>`<option value=${g.id}>${RN[g.round]} · ${esc(g.name)}</option>`).join('')}</select><input name=d type=date required aria-label=Date><input name=t type=time value="17:00" required aria-label=Time><input name=v placeholder=Venue><input name=l placeholder="Custom name (optional)"><button class="btn p">Pick two teams</button></form>`+S.fixtures.map(f=>`<div class="card pad"><div class="f sb"><span><b>${esc(nm(f))}</b><br><span class=mut>${RN[f.round]} · ${f.date||''} ${f.time||''} · ${esc(f.venue||'')}</span></span><button class=btn onclick="S.fixtures=S.fixtures.filter(x=>x.id!='${f.id}');commit()">Delete</button></div><p class=f><button class=btn onclick="xiPick('${f.id}','A')">XI ${esc(T(S,f.a)?.name)} (${(f.xiA||[]).length}/${n})</button><button class=btn onclick="xiPick('${f.id}','B')">XI ${esc(T(S,f.b)?.name)} (${(f.xiB||[]).length}/${n})</button></p></div>`).join('')}
const nm=m=>m.label||T(S,m.a)?.name+' vs '+T(S,m.b)?.name;
function pk(k){pick(id=>{tmp[k]=id;draw()},false,[tmp[k=='a'?'b':'a']])}
function go1(){const c=cfg(S),f=S.fixtures.find(x=>x.id==tmp.f),a=f?f.a:tmp.a,b=f?f.b:tmp.b;if(!a||!b)return alert('Select both teams.');
 const auto=t=>[...T(S,t).players].sort((p,q)=>p.no-q.no).slice(0,c.xi).map(p=>p.id),xa=f?f.xiA||[]:auto(a),xb=f?f.xiB||[]:auto(b);
 if(xa.length!=c.xi||xb.length!=c.xi)return alert(`Each team needs exactly ${c.xi} playing players. ${f?'Set the playing XI on the fixture.':'Add more players to each squad.'}`);
 const bf=$('#bf').value;S.live={id:uid(),fid:f?.id||null,a,b,xi:{[a]:xa,[b]:xb},maxW:c.xi-1,overs:+$('#ov').value||c.overs,round:f?f.round:$('#rd').value,group:f?.group||null,date:f?.date||new Date().toISOString().slice(0,10),venue:f?.venue||'',label:f?.label||'',cur:0,status:'live',inn:[newInn(bf,bf==a?b:a)]};snaps=[];pend=P0();tmp={};commit()}
function vStart(){const c=cfg(S),f=S.fixtures.find(x=>x.id==tmp.f),a=T(S,f?f.a:tmp.a),b=T(S,f?f.b:tmp.b);return`<h2>Start a battle</h2><p class=f><select onchange="tmp.f=this.value;draw()"><option value="">Manual: pick two teams</option>${S.fixtures.map(x=>`<option value=${x.id} ${x.id==tmp.f?'selected':''}>${esc(nm(x))} · ${x.date||''}</option>`).join('')}</select></p>${f?'':`<div class=f><button class=btn onclick="pk('a')">${a?esc(a.name):'Select team A'}</button><button class=btn onclick="pk('b')">${b?esc(b.name):'Select team B'}</button></div>`}<p class=f>${f?'':`<select id=rd>${ropt()}</select>`}<input id=ov type=number min=1 value=${c.overs} style="width:96px" aria-label=Overs> overs${a&&b?`<select id=bf><option value=${a.id}>${esc(a.name)} bats first<option value=${b.id}>${esc(b.name)} bats first</select>`:''}</p><button class="btn p" onclick=go1()>Start battle</button>`}
const cur=()=>{const M=S.live;return M.inn[M.cur]};
function setR(k,v){const i=cur();i[k]=v||null;if(v&&k!='bowler'&&!i.bt[v]){i.bt[v]={r:0,b:0,f:0,s:0,out:false};i.order.push(v)}commit()}
const tg=k=>{pend[k]=pend[k]?0:1;if(k=='wd')pend.nb=0;if(k=='nb')pend.wd=0;draw()},rn=n=>{pend.runs=n;draw()};
function label(p){return(p.wd?'WD'+(p.runs?'+'+p.runs:''):p.nb?'NB'+(p.runs?'+'+p.runs:''):p.out?'W':p.runs||'•')+(p.out&&(p.wd||p.nb)?'+W':'')}
function conf(){const M=S.live,i=cur(),p=pend;if(!i.striker||!i.non||!i.bowler)return alert('Select the striker, non-striker and bowler first.');
 snaps.push(JSON.stringify(i));if(snaps.length>10)snaps.shift();
 if(i.overDone){i.over=[];i.overDone=false}
 const bid=i.bowler,legal=!p.wd&&!p.nb,bat=p.wd?0:p.runs,ex=(p.wd?1+p.runs:0)+(p.nb?1:0),tot=bat+ex,b=i.bt[i.striker],w=i.bw[i.bowler]||(i.bw[i.bowler]={b:0,r:0,w:0,m:0,wd:0,nb:0,or:0});
 i.runs+=tot;i.extras+=ex;if(p.wd)i.ex.wd+=1+p.runs;if(p.nb)i.ex.nb++;
 if(!p.wd){b.b++;b.r+=bat;if(bat==4)b.f++;if(bat==6)b.s++}
 w.r+=tot;w.or+=tot;if(p.wd)w.wd++;if(p.nb)w.nb++;if(legal){w.b++;i.balls++}
 i.partner+=tot;i.over.push({l:label(p),w:!!p.out});
 const endOver=legal&&i.balls%6==0;let sw=(p.wd?p.runs:bat)%2==1;
 if(endOver){if(w.or==0)w.m++;w.or=0;i.prog.push(i.runs);i.overDone=true;i.bowler=null;sw=!sw}
 if(p.out){const slot=p.who=='non'?'non':'striker',o=i[slot];i.wkts++;i.bt[o].out=true;i.bt[o].how=p.ro?'run out':'b '+pn(S,i.bowl,bid);if(!p.ro)w.w++;i.partner=0;i[slot]=null;i.need=slot;i.pendSwap=endOver}
 else if(sw)[i.striker,i.non]=[i.non,i.striker];
 pend=P0();commit()}
function newBat(id){const i=cur();i[i.need]=id;i.bt[id]={r:0,b:0,f:0,s:0,out:false};i.order.push(id);if(i.pendSwap)[i.striker,i.non]=[i.non,i.striker];i.need=null;i.pendSwap=false;commit()}
function undo(){if(!snaps.length)return alert('Nothing to undo.');S.live.inn[S.live.cur]=JSON.parse(snaps.pop());commit()}
function endInn(){const M=S.live;if(M.cur==0){if(!confirm('End the first innings and start the chase?'))return;const a=M.inn[0];M.inn.push(newInn(a.bowl,a.bat));M.cur=1;snaps=[];pend=P0();commit()}
 else{if(!confirm('End the match?'))return;const[x,y]=M.inn,n1=T(S,x.bat).name,n2=T(S,y.bat).name;
  if(y.runs>x.runs){M.win=y.bat;M.result=`${n2} won by ${M.maxW-y.wkts} wickets${M.overs*6>y.balls?` (with ${M.overs*6-y.balls} balls remaining)`:''}`}else if(x.runs>y.runs){M.win=x.bat;M.result=`${n1} won by ${x.runs-y.runs} runs`}else{M.win=null;M.result='Match tied'}
  M.status='ended';commit()}}
function archive(){const M=S.live;S.history.push({...M,archived:true});S.fixtures=S.fixtures.filter(f=>f.id!=M.fid);S.live=null;commit()}
function vScore(M){const i=cur(),bt=T(S,i.bat),bw=T(S,i.bowl),p=pend,o=(list,v,ex)=>'<option value="">Select</option>'+list.filter(x=>x.id!=ex).map(x=>`<option value="${x.id}" ${x.id==v?'selected':''}>${esc(x.name)}</option>`).join('');
 const can=bt.players.filter(x=>M.xi[i.bat].includes(x.id)&&!i.bt[x.id]?.out),done=i.balls>=M.overs*6||i.wkts>=M.maxW||(M.cur==1&&i.runs>M.inn[0].runs);
 return`<div class="card pad"><div class="f sb"><span class=f>${logo(bt)}<b>${esc(bt.name)}</b> <span class=mut>${RN[M.round]} · ${M.cur?'2nd':'1st'} innings</span></span><span class=big>${i.runs}/<span class=wk>${i.wkts}</span> (${ov(i.balls)}/${M.overs})</span></div>${M.cur?`<div class=mut>Target ${M.inn[0].runs+1}</div>`:''}${done?'<p class=wk>Innings complete. Press End innings.</p>':''}
 <div class="f" style="margin-top:8px"><label>Striker<br><select onchange="setR('striker',this.value)">${o(can,i.striker,i.non)}</select></label><label>Non-striker<br><select onchange="setR('non',this.value)">${o(can,i.non,i.striker)}</select></label><label>Bowler<br><select onchange="setR('bowler',this.value)">${o(bw.players.filter(x=>M.xi[i.bowl].includes(x.id)),i.bowler)}</select></label></div></div>
 <div class="card pad"><div class=lab>This over</div><div class=balls>${i.over.map(b=>`<span class="ball ${b.w?'w':''}">${b.l}</span>`).join('')||'-'}</div>
 <p class=f>${[0,1,2,3,4,5,6,7].map(n=>`<button class="btn ${p.runs==n?'on':''}" onclick=rn(${n})>${n}</button>`).join('')}</p>
 <p class=f><button class="btn ${p.wd?'on':''}" onclick="tg('wd')">WD</button><button class="btn ${p.nb?'on':''}" onclick="tg('nb')">NB</button><button class="btn ${p.out?'on':''}" onclick="tg('out')">OUT</button>${p.out?`<button class="btn ${p.ro?'on':''}" onclick="tg('ro')">Run out</button><select onchange="pend.who=this.value"><option value=st>Striker out<option value=non ${p.who=='non'?'selected':''}>Non-striker out</select>`:''}</p>
 <p>Pending ball: <b>${label(p)}</b>${p.wd?` (wide, ${1+p.runs} to extras)`:p.nb?` (no ball, ${p.runs} off the bat)`:''}</p><div class=f><button class="btn p" onclick=conf()>Confirm ball</button><button class=btn onclick="pend=P0();draw()">Clear</button><button class=btn onclick=undo()>Edit last ball (undo)</button><button class=btn onclick=endInn()>${M.cur?'End match':'End innings'}</button></div></div>${batTable(S,i)}${bowlTable(S,i)}`}
function vEnded(M){return`<h2>${esc(M.result)}</h2><p class=mut>${esc(T(S,M.a)?.name)} ${M.inn[0].runs}/${M.inn[0].wkts} · ${esc(T(S,M.b)?.name)} ${M.inn[1].runs}/${M.inn[1].wkts}</p><label class=f><input type=checkbox onchange=archive() style="width:24px;min-height:24px"> Display in Match History (adds it to the Points Table)</label>`}
function vLive(){const M=S.live;let h=!M?vStart():M.status=='ended'?vEnded(M):vScore(M);
 if(M&&M.status=='live'){const i=cur();if(i.need){const bt=T(S,i.bat),r=bt.players.filter(x=>M.xi[i.bat].includes(x.id)&&!i.bt[x.id]);h+=`<div class=md><div class=box><h3>New batter</h3>${r.map(x=>`<button class=row onclick="newBat('${x.id}')">${esc(x.name)} <span class=mut>&nbsp;${x.role}</span></button>`).join('')||'<p>No batters left. End the innings.</p>'}${r.length?'':`<button class=btn onclick="cur().need=null;commit()">Close</button>`}</div></div>`}}return h}
function vSetup(){const c=cfg(S);return`<h2>Tournament setup</h2><form class=fg onsubmit="saveSetup(event)">${[['name','Tournament name',c.name,'text'],['sub','Subtitle',c.sub,'text'],['maxTeams','Total teams allowed',c.maxTeams,'number'],['gpr','Groups per round',c.gpr,'number'],['tpg','Teams per group',c.tpg,'number'],['overs','Overs per innings',c.overs,'number'],['squad','Squad size (max players per team)',c.squad,'number'],['xi','Playing players per side',c.xi,'number'],['rounds','Round names, comma separated (last is the final)',c.rounds.map(r=>r.name).join(', '),'text']].map(([k,l,v,t])=>`<label class=fl>${l}<input name=${k} type=${t} value="${esc(v)}" ${t=='number'?'min=1':''} required></label>`).join('')}<button class="btn p">Save setup</button></form><p class=mut>Maximum wickets per innings = playing players minus 1. Limits are enforced when adding teams, players, groups and starting a battle.</p>`}
function saveSetup(e){e.preventDefault();const f=e.target.elements,g=k=>f[k].value.trim(),n=k=>+f[k].value,names=g('rounds').split(',').map(x=>x.trim()).filter(Boolean);
 if(!names.length)return alert('Add at least one round.');if(n('xi')<2)return alert('A side needs at least 2 playing players.');if(n('xi')>n('squad'))return alert('Playing players cannot exceed the squad size.');
 S.settings={name:g('name'),sub:g('sub'),maxTeams:n('maxTeams'),gpr:n('gpr'),tpg:n('tpg'),overs:n('overs'),squad:n('squad'),xi:n('xi'),rounds:names.map((x,k)=>({id:k==names.length-1&&names.length>1?'final':'r'+(k+1),name:x}))};commit()}
function vArchive(){return`<h2>Match archive</h2>`+(S.history.map(h=>`<div class="card pad f sb"><span><b>${esc(nm(h))}</b><br><span class=mut>${RN[h.round]} · ${h.date||''}</span><br>${esc(h.result)}</span><button class=btn onclick="if(confirm('Delete this match from history?')){S.history=S.history.filter(x=>x.id!='${h.id}');commit()}">Delete</button></div>`).join('')||'<p class=mut>No archived matches yet.</p>')}
function draw(){const a=$('#app');document.body.className='adm';
 if(!tok){a.innerHTML=`<main style="max-width:360px;padding-top:15vh"><h1>Admin</h1><p class=mut>ECSC Challenge Trophy 2026</p><form onsubmit="login(event)" class=f><input name=pw type=password placeholder=Password required autofocus><button class="btn p">Log in</button></form><p id=err class=wk></p></main>`;return}
 if(!S)return boot();syncRN(S);
 const V={setup:vSetup,teams:vTeams,groups:vGroups,fixtures:vFix,live:vLive,archive:vArchive};
 a.innerHTML=`<nav class=nav>${[['setup','Tournament Setup'],['teams','Teams & Players'],['groups','Groups'],['fixtures','Battles & Fixtures'],['live','Live Scoring'],['archive','Match Archive']].map(([k,n])=>`<a href=# onclick="view='${k}';draw();return false" class="${view==k?'on':''}">${n}</a>`).join('')}<span class=sp></span><a href="/" target=_blank>View site</a><a href=# onclick="logout();return false">Logout</a></nav><main>${V[view]()}</main>`}
draw();
